version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3001:${PORT}
    environment:
      - DB_HOST=db  
    depends_on:
      - db
    volumes:
    - .:/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

volumes: 
 data: {}
