version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3001:${PORT}
    environment:
      - DB_HOST=db  
    depends_on:
      - db
    volumes:
    - .:/app   # change in . directory should be reflected in /app directory  inside conatiner 

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db  # i am storing this vloume data to /data/db directory as to maintain the data as conatiners are till their running lifetime only
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

volumes: 
 data: {}    # this is data volume or data that is used bw containers 


# when i will use docker-compose down this will delete the volumes includeing the copied files and the plsql data 
# one way is to use host file sysytem to save the data if done that it will loose the portabolity
#second way is to create another separet conatiner and run it separately from api and do not down that container